<?php

namespace AppBundle\DataFixtures\ORM;

use Faker\Provider\Base as BaseProvider;
use Faker\Generator;

class ProductProvider extends BaseProvider
{

    public function __construct(Generator $generator)
    {
        parent::__construct($generator);
    }

    public function productCategory()
    {
        $key = array_rand($this->categories);
        return $this->categories[$key];
    }

    public function productList()
    {
        $key = array_rand($this->products);
        return $this->products[$key];
    }

    private $categories = [
        "Велотренажеры",
        "Орбитреки",
        "Беговые дорожки",
        "Гребные тренажеры",
        "Степперы",
        "Байк-станции",
        "Гантели, гири, утяжелители",
        "Штанги, грифы, диски",
        "Атлетические пояса",
        "Эспандеры",
        "Перчатки для фитнеса, культуризма",
        "Мячи для фитнеса",
        "Фитнес-джамперы",
        "Аквафитнес",
        "Коврики, маты",
        "Товары для фитнеса, гимнастики",
        "Йога, пилатес",
        "Экипировка для бокса и единоборств",
        "Обувь для тренировок",
        "Тренировочные ножи",
        "Пульсометры",
        "Шагомеры",
        "Спортивные часы",
        "Фитнес-трекеры",
    ];

    private $products = [
        "Беговая дорожка InterFit Грейс KL-1316A",
        "Беговая дорожка Torneo Inita (T-150)",
        "Беговая дорожка Jada FITNESS JS-4500",
        "Беговая дорожка InterFit ДЖЕССИ KL-803",
        "Беговая дорожка FitLogic Miracle T581",
        "Беговая дорожка DISCOVERY F-16",
        "Беговая дорожка Esprit CT50",
        "Беговая дорожка FitLogic D225",
        "Беговая дорожка USA Style SS-50A",
        "Беговая дорожка USA Style SS-ET-0901",
        "Беговая дорожка Spirit Esprit XT-185",
        "Беговая дорожка JKexer Fitlux 365",
        "Беговая дорожка EuroFit DALLAS",
        "Беговая дорожка Torneo Linia (T-203)",
        "Беговая дорожка Horizon Fitness ADVENTURE 2 PLUS",
        "Беговая дорожка InterFit KL-830 ПРОГРЕСС",
        "Беговая дорожка EuroFit SIESTA",
        "Беговая дорожка Spirit Esprit XT-385",
        "Беговая дорожка Horizon Fitness ADVENTURE 5 PLUS",
        "Беговая дорожка InterFit Сантана KL-1301",
        "Беговая дорожка Horizon Fitness ADVENTURE 3 PLUS",
        "Беговая дорожка HouseFit HT 9051",
        "Беговая дорожка USA Style SS-205-1",
        "Беговая дорожка магнитная USA Style SS-401",
        "Беговая дорожка Jada FITNESS MT20",
        "Беговая дорожка магнитная USA Style SS-301",
        "Беговая дорожка магнитная USA Style SS-201",
        "Беговая дорожка Torneo Cross (T-107-M)",
        "Беговая дорожка HouseFit HSF-425 M",
        "Беговая дорожка HouseFit HT 9052HP",
        "Беговая дорожка Torneo SPRINT (T-115)",
        "Беговая дорожка Torneo Sprint (T-115)",
        "Беговая дорожка Jada FITNESS JS-203251",
        "Беговая дорожка InterFit ОМА 797К",
        "Беговая дорожка HouseFit DH 84224P",
        "Беговая дорожка HouseFit HT 9127",
        "Беговая дорожка HouseFit HT 9127LHP",
        "Беговая дорожка HouseFit HT 9128",
        "Беговая дорожка Torneo Smarta (T-205)",
        "Беговая дорожка USA Style SS-10A",
        "Беговая дорожка Jada FITNESS T-110",
        "Беговая дорожка HouseFit HТ 9114HP",
        "Беговая дорожка Vigor XPL350",
        "Беговая дорожка Vigor XPL400",
        "Беговая дорожка HouseFit HТ 9098HP",
        "Беговая дорожка Sprint ST305",
        "Беговая дорожка USA Style SS-70M",
        "Беговая дорожка USA Style SS-T27",
        "Беговая дорожка USA Style SS-1300",
        "Беговая дорожка HouseFit HТ 9115HP",
        "Беговая дорожка USA Style SS-1830",
        "Беговая дорожка Esprit ST60",
        "Беговая дорожка Jada FITNESS JS-164027",
        "Беговая дорожка Jada FITNESS JS-164016",
        "Беговая дорожка Life Gear 97410",
        "Беговая дорожка Vigor XPL500",
        "Беговая дорожка Life Gear 97020 Walkease Professional",
        "Беговая дорожка HouseFit D120 FREEWILL",
        "Беговая дорожка Jada FITNESS JS-10431",
        "Беговая дорожка Torneo Nota (T-307)",
        "Беговая дорожка USA Style SS-77A",
        "Беговая дорожка USA Style SS-T51",
        "Беговая дорожка Vigor XPL550",
        "Беговая дорожка USA Style SS-1831",
        "Беговая дорожка Sprint ST315",
        "Беговая дорожка USA Style SS-T26",
        "Беговая дорожка Esprit ST70",
        "Беговая дорожка USA Style SS-1365",
        "Беговая дорожка Jada FITNESS JS-10430",
        "Беговая дорожка Life Gear VELOSSA (97455)",
        "Беговая дорожка Sprint ST310M",
        "Беговая дорожка HouseFit HT 9073HP",
        "Беговая дорожка Vigor T-8403",
        "Беговая дорожка USA Style SS-88B",
        "Беговая дорожка USA Style WNQ SS-2000Q",
        "Беговая дорожка InterFit TD 343A",
        "Беговая дорожка Torneo Magic (T-410)",
        "Беговая дорожка Vigor T-8430",
        "Беговая дорожка USA Style WNQ SS-2000L",
        "Беговая дорожка InterFit HX-0910BS",
        "Беговая дорожка Life Gear 98400",
        "Беговая дорожка FitLogic R115",
        "Беговая дорожка HouseFit HT 9121HP",
        "Беговая дорожка InterFit AP-100BS",
        "Беговая дорожка Vigor T-8450",
        "Беговая дорожка USA Style SS-33B",
        "Беговая дорожка HouseFit HT 9073E1",
        "Беговая дорожка Esprit CT80",
        "Беговая дорожка FitLogic R270",
        "Беговая дорожка HouseFit R170 MIRACLE",
        "Беговая дорожка EuroFit Pacifica 1610 СА",
        "Беговая дорожка USA Style WNQ SS-5000J",
        "Беговая дорожка Jada FITNESS JS-5000A",
        "Беговая дорожка USA Style WNQ SS-5000L",
        "Беговая дорожка FitLogic R280",
        "Беговая дорожка HouseFit D160 FREEWILL",
        "Беговая дорожка BH Fitness F1 (G6414V)",
        "Беговая дорожка EuroFit Pacifica 1650 ЕА",
        "Беговая дорожка Torneo Tanga (T-710)",
        "Беговая дорожка Sprint ST500",
        "Беговая дорожка DISCOVERY F-18",
        "Беговая дорожка HouseFit V160 MIRACLE",
        "Беговая дорожка InterFit KL-1312 САЛЛИ",
        "Беговая дорожка HouseFit HT 9126HP",
        "Беговая дорожка NordicTrack Т 8.0",
        "Беговая дорожка DISCOVERY F-22",
        "Беговая дорожка Esprit CT100",
        "Беговая дорожка Vigor T-8501E",
        "Беговая дорожка EuroFit PHANTOM 2620 СА",
        "Беговая дорожка NordicTrack Т 9.1",
        "Беговая дорожка FitLogic V570",
        "Беговая дорожка EuroFit DETROIT",
        "Беговая дорожка FitLogic Miracle V550",
        "Беговая дорожка BH Fitness CRUISER V50 (G6250)",
        "Беговая дорожка NordicTrack Т 7.2",
        "Беговая дорожка FitLogic V380",
        "Беговая дорожка InterFit KL 1319 РОЛЛИНГ",
        "Беговая дорожка Jkexer Fitlux 555",
        "Беговая дорожка USA Style WNQ SS-5000L TV",
        "Беговая дорожка FitLogic Miracle V370",
        "Беговая дорожка USA Style SS-67",
        "Беговая дорожка HouseFit V390/395 MIRACLE",
        "Беговая дорожка NordicTrack Т 9.2",
        "Беговая дорожка Torneo Correra (T-750)",
        "Беговая дорожка FitLogic V395",
        "Беговая дорожка Esprit ST100",
        "Беговая дорожка NordicTrack T13.0",
        "Беговая дорожка BH Fitness F3 (G6425)",
        "Беговая дорожка Jkexer Fitlux 575",
        "Беговая дорожка Spirit Esprit XT-285",
        "Беговая дорожка EuroFit SEBRING",
        "Беговая дорожка BH Fitness S Pro (G6322)",
        "Беговая дорожка USA Style SS-67A+TV",
        "Беговая дорожка NordicTrack T14.2",
        "Беговая дорожка DISCOVERY MOTION 6.0",
        "Беговая дорожка NordicTrack T15.0",
        "Беговая дорожка Kettler TRACK MOTION (7881-300)",
        "Беговая дорожка EuroFit DAYTONA",
        "Беговая дорожка Spirit Esprit XT-685",
        "Беговая дорожка Spirit Esprit XT-485",
        "Беговая дорожка Horizon Fitness Elite T3000",
        "Беговая дорожка BH Fitness Explorer Evolution (G637)",
        "Беговая дорожка FitLogic OpenArm 3000",
        "Беговая дорожка Horizon Fitness Elite T5000",
        "Беговая дорожка BH Fitness Marathon (G652)",
        "Беговая дорожка NordicTrack T20.0",
        "Беговая дорожка Kettler TRACK PERFORMANCE (7885-300)",
        "Беговая дорожка Circle Fitness M6000",
        "Беговая дорожка NordicTrack T22",
        "Беговая дорожка NordicTrack X7I",
        "Беговая дорожка Kettler TRACK EXPERIENCE (7885-600)",
        "Беговая дорожка Circle Fitness M7200 LUXURY",
        "Беговая дорожка SportsArt Т625",
        "Беговая дорожка Circle Fitness М7200",
        "Беговая дорожка SportsArt ТR-35",
        "Беговая дорожка SportsArt T613",
        "Беговая дорожка Vision Fitness T60 PRO",
        "Беговая дорожка Matrix T50X",
        "Беговая дорожка SportsArt Т650",
        "Беговая дорожка Matrix T3X (2012)",
        "Беговая дорожка Matrix T3X",
        "Беговая дорожка Body Sculpture Эконом BT 3150S3IKO-C-Z3",
        "Беговая дорожка NordicTrack Т 7.0 NETL 81810",
        "Беговая дорожка Body Sculpture ВТ-2740",
        "Беговая дорожка Torneo Maestra (T-311)",
        "Беговая дорожка Torneo Sprint (T-111)",
        "Беговая дорожка Horizon Fitness ADVENTURE 4 PLUS",
        "Беговая дорожка DISCOVERY Run 4.0",
        "Беговая дорожка EuroFit TALENT 7400А",
        "Беговая дорожка Kettler Marathon TX5",
        "Беговая дорожка Vision Fitness T9250 Simple",
        "Беговая дорожка Horizon Fitness Evolve",
        "Министадион USA Style SS-0090",
        "Беговая дорожка Horizon Fitness Elite T4000",
        "Беговая дорожка Horizon Fitness Elite T608",
        "Беговая дорожка Life Gear PACER (97015)",
        "Беговая дорожка Jada FITNESS JS-4001",
        "Беговая дорожка HouseFit HТ 9105HP",
        "Беговая дорожка SportsArt T631",
        "Беговая дорожка Horizon Fitness Adventure 4",
        "Беговая дорожка Body Sculpture Ранк ВТ-5400",
        "Беговая дорожка Jada FITNESS JS-9403",
        "Беговая дорожка Torneo Forma (T-160)",
        "Беговая дорожка Horizon Fitness Rojo 4",
        "Беговая дорожка BH Fitness F0 (G6434)",
        "Беговая дорожка EuroFit LX8-47",
        "Беговая дорожка EuroFit LX6-47",
        "Беговая дорожка Horizon Fitness Adventure 2",
        "Беговая дорожка BH Fitness F5 (G6427V)",
        "Беговая дорожка EuroFit SX3-T2",
        "Беговая дорожка Horizon Fitness Rojo 5",
        "Беговая дорожка EuroFit DX13-B1",
        "Беговая дорожка Horizon Fitness TI 32",
        "Беговая дорожка NordicTrack T23",
        "Беговая дорожка Life Gear TM8407 Plusominus",
        "Беговая дорожка Vision Fitness T9550 Premier",
        "Беговая дорожка Horizon Fitness Elite 407",
        "Беговая дорожка Kettler Boston XL (7887-600)",
        "Беговая дорожка NordicTrack T14.2",
        "Беговая дорожка SportsArt TR33",
        "Беговая дорожка SportsArt T670",
        "Беговая дорожка BH Fitness F1 (G6415)",
        "Беговая дорожка EuroFit MODERN 7950",
        "Беговая дорожка Body Sculpture Империя BT 3151S3P-C-Z2",
        "Беговая дорожка Life Gear TM 8403",
        "Беговая дорожка Jada FITNESS JS-16400",
        "Беговая дорожка EuroFit DX3-A5",
        "Беговая дорожка SportsArt T680",
        "Беговая дорожка EuroFit FOCUS 8010А",
        "Беговая дорожка NordicTrack T25",
        "Беговая дорожка Life Gear ACAMAR (97780)",
        "Беговая дорожка EuroFit DX6-C1",
        "Орбитрек Kettler Cross M (7647-800)",
        "Орбитрек Kettler Rivo M (7643-000)",
        "Орбитрек Kettler Vito M (7658-000)",
        "Орбитрек Kettler Unix M (7650-100)",
        "Орбитрек Kettler Unix P (7652-000)",
        "Орбитрек Kettler Elyx 5 (7655-500)",
        "Орбитрек Kettler Unix Ex (7670-500)",
        "Орбитрек Kettler Vito XLS",
        "Орбитрек Kettler Axos Cross M (7647-800)",
        "Орбитрек Kettler Satura E EXT",
        "Орбитрек Kettler Satura P",
        "Орбитрек Kettler Vito XS",
        "Орбитрек Kettler CTR3",
    ];
}
